import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import QueryClientProviderContext from "./query-client-provider";
import { Toaster } from "sonner";

const MontserratSans = Montserrat({
	variable: "--font-monteserrat-sans",
	subsets: ["latin"],
	weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
	title: "HYDRA VR",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${MontserratSans.className} antialiased`}>
				<main className="">
					<QueryClientProviderContext>{children}</QueryClientProviderContext>
					<Toaster />
				</main>
			</body>
		</html>
	);
}
