import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const MontserratSans = Montserrat({
  variable: "--font-monteserrat-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "HYDRA VR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${MontserratSans.className} antialiased`}>
        <Header/>
        <main className="container mx-auto lg:px-24 px-4">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}